# -*- coding: utf-8 -*-

"""
    apimaticcalculatorlib.apimatic_calculator_client

    This file was automatically generated by APIMATIC BETA v2.0 on 09/28/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class APIMATICCalculatorClient(object):

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()



